### ISSUE TITLE
Receive Texture

### ISSUE THREAD

**Issue by kanimaru** [you-win/spout-gd#12]
Hi is there an example to receive a texture?

Tried this but only get a pink plane.

```
extends MeshInstance3D

var spout = Spout.new()

var tex: ImageTexture = ImageTexture.new()
var mat: StandardMaterial3D
var handle: int
func _ready() -> void:
	spout.set_receiver_name("Spout_OBS_Filter")
	print(spout.is_sender_connected()) # Return false?
	mat = get_surface_override_material(0)
	handle = RenderingServer.texture_get_native_handle(tex)
	mat.albedo_texture = tex
	mat.emission_texture = tex

func _process(delta: float) -> void:
	if spout.is_updated():
		spout.receive_texture(handle)
```

**Comment by erodozer** [comment]
Is your project set to use the Compatibility (OpenGL) renderer?  `receive_texture` in spout only works with OpenGL texture handle, however if you're using the Forward+ renderer it'll supply Vulkan ids.  If you do not wish to change off of the Vulkan renderer, then you can use `receive_image` instead, though it is less performant due to CPU overhead of the operation.

**Comment by kanimaru** [comment]
Yeah I use currently Vulkan. How would receive_image work cause I tried this also without success: 
```gdscript
extends MeshInstance3D

var spout = Spout.new()

var tex: ImageTexture = ImageTexture.new()
var mat: StandardMaterial3D

func _ready() -> void:
	mat = get_surface_override_material(0)
	mat.albedo_texture = tex
	mat.emission_texture = tex

func _process(delta: float) -> void:
	if spout.is_updated():
		var image = Image.create(3440,1440,true,Image.FORMAT_RGBA8)
		spout.receive_image(image, Spout.FORMAT_RGBA)
		tex.set_image(image)
	
```
was not working 

More Informations `spout.is_sender_connected()` always returns false.
I tried to go compatibility mode in godot to use opengl but got none of the both working. I use the example spout sender and tried also with OBS Plugin Sender both didn't worked. 

Can you provide anyway to receive a image via Spout please?

**Comment by erodozer** [comment]
When working with spout you receiver name needs to match exactly with what the spout source is using.

![image](https://github.com/you-win/spout-gd/assets/316728/f70f0710-dd3b-4877-8772-726f712c7d90)

In this case I would have to use
```
spout.set_sender_name("OBS_Game")
```

If your source is not actually sending anything, or if the name doesn't match exactly, then sender may appear as closed.  Also is_sender_connected is an asynchronous state, so it may appear as false when you first set the sender name, if you poll it in _process you may see it change to true.

Also, when creating an image, it's important to use the exact same dimensions as what the spout sender says it has, so that it may arrange the data properly.
```
Image.create(spout.get_sender_width(), spout.get_sender_height(), true, Image.FORMAT_RGBA8)
```

If you're still having trouble, you can also check out my fork which has some helper texture resources to handle the most common use-cases.
https://github.com/erodozer/spout-gd
https://github.com/erodozer/spout-gd/releases/tag/latest

**Comment by kanimaru** [comment]
Your Spout Texture did the thing BIG THX <3
